// <auto-generated />
using System;
using LogicaDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaDatos.Migrations
{
    [DbContext(typeof(DbContextApp))]
    [Migration("20250625003711_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspecialidadProfesional", b =>
                {
                    b.Property<int>("EspecialidadesId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesionalesId")
                        .HasColumnType("int");

                    b.HasKey("EspecialidadesId", "ProfesionalesId");

                    b.HasIndex("ProfesionalesId");

                    b.ToTable("EspecialidadProfesional");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<int>("EstablecimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAsistencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GrupoMuscular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.EjercicioRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RutinaEjercicioId")
                        .HasColumnType("int");

                    b.Property<bool>("SeRealizo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaEjercicioId");

                    b.ToTable("EjercicioRealizadosPorClientes");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEspecialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int?>("EstablecimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicacionId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPrivada")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vistas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRutina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.SesionRutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionMin")
                        .HasColumnType("int");

                    b.Property<int?>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinasRealizadasClientes");
                });

            modelBuilder.Entity("LogicaNegocio.Extra.SerieRealizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EjercicioRealizadoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int");

                    b.Property<float?>("PesoUtilizado")
                        .HasColumnType("real");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioRealizadoId");

                    b.ToTable("SeriesParaEjerciciosDeCliente");
                });

            modelBuilder.Entity("EspecialidadProfesional", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Especialidad", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Profesional", null)
                        .WithMany()
                        .HasForeignKey("ProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Cita", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Especialidad", "Especialidad")
                        .WithMany("Citas")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Establecimiento", "Establecimiento")
                        .WithMany("Citas")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany("Citas")
                        .HasForeignKey("ProfesionalId");

                    b.Navigation("Cliente");

                    b.Navigation("Especialidad");

                    b.Navigation("Establecimiento");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Comentario", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Admin", "Admin")
                        .WithMany("Comentarios")
                        .HasForeignKey("AdminId");

                    b.HasOne("LogicaNegocio.Clases.Cliente", "Cliente")
                        .WithMany("Comentarios")
                        .HasForeignKey("ClienteId");

                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany("Comentarios")
                        .HasForeignKey("ProfesionalId");

                    b.HasOne("LogicaNegocio.Clases.Publicacion", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Ejercicio", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany("Ejercicios")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.EjercicioRealizado", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.SesionRutina", "RutinaEjercicio")
                        .WithMany("EjericiosRealizados")
                        .HasForeignKey("RutinaEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("RutinaEjercicio");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Media", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("LogicaNegocio.Clases.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("LogicaNegocio.Clases.Ejercicio", "Ejercicio")
                        .WithMany("Medias")
                        .HasForeignKey("EjercicioId");

                    b.HasOne("LogicaNegocio.Clases.Establecimiento", "Establecimiento")
                        .WithMany("Media")
                        .HasForeignKey("EstablecimientoId");

                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId");

                    b.HasOne("LogicaNegocio.Clases.Publicacion", "Publicacion")
                        .WithMany("ListaMedia")
                        .HasForeignKey("PublicacionId");

                    b.Navigation("Admin");

                    b.Navigation("Cliente");

                    b.Navigation("Ejercicio");

                    b.Navigation("Establecimiento");

                    b.Navigation("Profesional");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Publicacion", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Admin", "Admin")
                        .WithMany("Publicaciones")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany("Publicaciones")
                        .HasForeignKey("ProfesionalId");

                    b.Navigation("Admin");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Rutina", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Cliente", null)
                        .WithMany("Rutinas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("LogicaNegocio.Clases.Profesional", "Profesional")
                        .WithMany("Rutinas")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.SesionRutina", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.Cliente", "Cliente")
                        .WithMany("SesionesEntrenadas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Clases.Ejercicio", null)
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId");

                    b.HasOne("LogicaNegocio.Clases.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("LogicaNegocio.Extra.SerieRealizada", b =>
                {
                    b.HasOne("LogicaNegocio.Clases.EjercicioRealizado", "EjercicioRealizado")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioRealizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioRealizado");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Admin", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Cliente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Comentarios");

                    b.Navigation("Rutinas");

                    b.Navigation("SesionesEntrenadas");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Ejercicio", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.EjercicioRealizado", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Especialidad", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Establecimiento", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Profesional", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Comentarios");

                    b.Navigation("Ejercicios");

                    b.Navigation("Publicaciones");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Publicacion", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("ListaMedia");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("LogicaNegocio.Clases.SesionRutina", b =>
                {
                    b.Navigation("EjericiosRealizados");
                });
#pragma warning restore 612, 618
        }
    }
}
